config/routes.rb
Rails.application.routes.draw do
  resources :newspapers
  resources :librarians
  resources :bookings
  resources :employees
  resources :users
  resources :libraries
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :employees

  def address
    logger.info("Library#address method reached")
    super
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  caches_page :index#, :show
  before_action :set_library, only: [:show, :edit, :update, :destroy]
  # libraries do not change that often,
  # so we use page caching on index

  # GET /libraries
  # GET /libraries.json
  def index
    logger.info("Libraries index reached")
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
        expire_page action: 'index'
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
        expire_page action: 'index'
        #expire_page action: 'show', id: @library.id
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
      expire_page action: 'index'
      #expire_page action: 'show', id: @library.id
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:address, :foundation_year)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library, local: true) do |form| %>
  <% if library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
        <% library.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :foundation_year %>
    <%= form.number_field :foundation_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libraries</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Foundation year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.address %></td>
        <td><%= library.foundation_year %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<% cache(@library) do %>
  <p>
    <strong>Address:</strong>
    <%= @library.address %>
  </p>

  <p>
    <strong>Foundation year:</strong>
    <%= @library.foundation_year %>
  </p>

  <p>
    <strong>Employees</strong>
    <%= render @library.employees %>
  </p>

  <%= link_to 'Edit', edit_library_path(@library) %> |
  <%= link_to 'Back', libraries_path %>
<% end %>